[features]
seeds = true
skip-lint = false
[programs.localnet]
contract = "GPbJzd35DJy3wxDnyzy3kdy4qFbNeBxhTMbs2erYkjJL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/saber/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
