[features]
seeds = false
skip-lint = false
[programs.localnet]
contract = "ErAmA79CeCw8RLQVKQasKSowveXuPfwQSSunm89ZM4fo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/saber/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
